#!/bin/bash

git fetch upstream && \
git checkout develop && \
git merge upstream/develop && \
git push && \
git checkout origin/master && \
git merge upstream/master && \
git push origin HEAD:master && \
git checkout origin/3.1-stable && \
git merge upstream/3.1-stable && \
git push origin HEAD:3.1-stable && \
git checkout develop
